<div id="div-xlista-<?=$listaId?>" class="div-xlista">

<table id="listaDados-<?=$listaId?>" cellpadding="0" cellspacing="0" width="99%" border="0" class="<?=implode ( " " , $tableClassList )?>" align="center">

    <? if ( $tableTitle ) : ?>
        <caption style="color:#FFF;background:#069">
        <!--<caption style="color:#FFF;background: linear-gradient(to bottom, #1e5799 0%,#2989d8 50%,#207cca 51%,#7db9e8 100%);">-->
            <?=$tableTitle?>

        </caption>
    <? endif ?>

    <thead>

        <tr>

            <? if ( !$UsaPaginacao && $showLineCounter ) : ?>
                <th class="listViewThS1" width="10">&nbsp;</th>
            <? endif ?>

            <? if ( !empty ( $checkbox['nome'] ) ) : ?>
                <td scope="col" class="listViewThS1" style="padding:0px" >
                    <input type="checkbox" id="chall" name="chall" onclick="fclistaDadosCheckAll(this,'<?=$checkbox['nome']?>[]')" style="display :<?=$checkboxValues[$indice]['display'] ?>" value="CHALL">
                </td>
            <? endif ?>

    <? /* COLUNAS ========================================================== */ ?>

            <? if ( !empty ( $arr_campos_exibicao ) ) foreach ( $arr_campos_exibicao as $sec ) : ?>
                <th scope="col"  class="listViewThS1" <?=($sec->getNowrap())?'nowrap':''?> align="<?=$sec->getAlign()?>" >
                    <slot>
                        <? if ( $ordenacao && $sec->allowOrder () ) : ?>
                            <a href="#" class="listViewThLinkS1" onClick="ordenacao<?=$listaId?>('<?=$sec->getNome()?>','<?=($sec->getOrder()==="DESC")?'ASC':'DESC'?>')">
                                <?=$sec->getLabel()?>
                                <? if ( $sec->getOrder() !== "" ) : ?>
									<? if ($order['TIPO']==="DESC") : ?>
										<span class="glyphicon glyphicon-chevron-up"></span>                                    
									<? else : ?>
										<span class="glyphicon glyphicon-chevron-down"></span>                                    
									<? endif ?>
                                <? else : ?>
                                <? endif ?>
                            </a>
                        <? else : ?>
                            <?=$sec->getLabel()?>
                        <? endif ?>
                    </slot>
                </th>
            <? endforeach ?>

        </tr>

    </thead>

    <tbody>

        <? $cor=$cont=0 ?>
        <? if ( !empty ( $arr_campos_exibicao_values ) ) foreach ( $arr_campos_exibicao_values as $indice => $arrDado ) : ?>
            <tr class="<?=($cor=!$cor)?'linha1ListaDados':'linha2ListaDados'?>" style="<?=$arrDado['Style']?>" >

                <? if ( !$UsaPaginacao && $showLineCounter ) : ?>
                    <td  width="40" align="center" style="<?=$UsaBackgroundIndex?>" >
                        <span style="text-align:center"><b><?=++$cont?></b></span>
                    </td>
                <? endif ?>

                <? if ( !empty ( $checkbox['nome'] ) ) : ?>
                    <td >
                        <span id="tlb_messagecheckbox<?=$checkboxValues[$indice]['valor']?>"></span>
                        <input type="checkbox" name="<?=$checkbox['nome']?>[]" style="display:<?=$checkboxValues[$indice]['display']?>" value="<?=$checkboxValues[$indice]['valor']?>">
                    </td>
                <? endif ?>

                <? if ( !empty ( $arr_campos_exibicao ) ) foreach ( $arr_campos_exibicao as $objCampo ) : ?>
                    <td valign="middle" <?=($objCampo->getNowrap())?'nowrap':''?> align="<?=$objCampo->getAlign()?>" style="<?=$arrDado['Style']?>" >
                        <slot>
                            <?=$arrDado[$objCampo->getNome()]?>
                        </slot>
                    </td>
                <? endforeach ?>

        <? endforeach ?>

        <? if ( $qry_pag_registros < 1 && $qtd_linha == 0 ) : ?>
            <tr align="center" height="20">
                <td colspan="<?=$total_colunas?>" class="oddListRowS1">

                	<br>
                	<strong>Nenhum Registro encontrado</strong>
                	<br>

                	<? if ( !empty ( $createPageLink ) && !empty ( $_POST[$listaId."FILTERS"] ) ) : ?>

	                	<form action="<?=$createPageLink?>" method="post">

	                		<? foreach ( $_POST[$listaId."FILTERS"] as $key => $value ) : ?>
								<input type="hidden" name="<?=$key?>" value="<?=$value?>">
							<? endforeach ?>

	                		<button type="submit" class="btn btn-default">
	                			<span class="glyphicon glyphicon-plus"></span>
	                			Inserir um novo registro
	                		</button>

	                	</form>

	                <? endif ?>

                	<br>

                </td>
            </tr>
        <? endif ?>

    </tbody>

    <tfoot>
        <tr>
            <td colspan="<?=$total_colunas?>" >

                <? if ( $UsaPaginacao ) : ?>
                    <div width="99%" style="text-align:right;float:left;">

                        <div class="btn-group">

                            <button class="btn btn-default btn-xs " type="button" onClick="pagina<?=$listaId?>('inicio')" <? if ( $paginacao['inicio'] !== '_on' ) : ?>disabled="disabled"<? endif ?> >
                                &nbsp;&nbsp;&nbsp;&nbsp; <span class="glyphicon glyphicon-fast-backward"></span> &nbsp;&nbsp;&nbsp;&nbsp;
                            </button>

                            <button class="btn btn-default btn-xs " type="button" onClick="pagina<?=$listaId?>('anterior')" <? if ( $paginacao['anterior'] !== '_on' ) : ?>disabled="disabled"<? endif ?> >
                                &nbsp;&nbsp;&nbsp;&nbsp; <span class="glyphicon glyphicon-step-backward"></span> &nbsp;&nbsp;&nbsp;&nbsp;
                            </button>

                            <button class="btn btn-default btn-xs" type="button" onclick="goToPage<?=$listaId?>()" <? if ( $qry_pag_paginas <= 1 ) : ?>disabled="disabled"<? endif ?> >
                                &nbsp;&nbsp;&nbsp;&nbsp; P&aacute;gina <?=$qry_pag_inicio?> de <?=$qry_pag_paginas?> &nbsp;&nbsp;&nbsp;&nbsp;
                            </button>

                            <button class="btn btn-default btn-xs " type="button" onClick="pagina<?=$listaId?> ('proximo')" <? if ( $paginacao['proxima'] !== '_on' ) : ?>disabled="disabled"<? endif ?> >
                                &nbsp;&nbsp;&nbsp;&nbsp; <span class="glyphicon glyphicon-step-forward"></span> &nbsp;&nbsp;&nbsp;&nbsp;
                            </button>

                            <button class="btn btn-default btn-xs " type="button" onClick="pagina<?=$listaId?> ('fim')" <? if ( $paginacao['fim'] !== '_on' ) : ?>disabled="disabled"<? endif ?> >
                                &nbsp;&nbsp;&nbsp;&nbsp; <span class="glyphicon glyphicon-fast-forward"></span> &nbsp;&nbsp;&nbsp;&nbsp;
                            </button>

                        </div>
                    </div>
                <? endif ?>

                <span style="float:right;">
                    <? if ( DEBUG ) : ?>
                        <button type="button" class="btn btn-xs btn-default" onclick="$('#linha-debug-query-<?=$listaId?>').toggle()"><span class="glyphicon glyphicon-search"></span> Inspecionar Query</button>
                        &nbsp;&nbsp;&nbsp;
                    <? endif ?>
                    Total: <?=$qry_pag_registros?> resultado<?=($qry_pag_registros>1)?"s":''?>
                </span>

            </td>
        </tr>

        <tr id="linha-debug-query-<?=$listaId?>" style="display:none;" >
            <td colspan="<?=$total_colunas?>" align="left">
<pre style="background:#000;color:#0F0;font-family:courier new;height:100%;width:100%;padding:10px;" >
<?=$query?>
</pre>
            </td>
        </tr>

    </tfoot>

</table>



</div>
<?=$javascriptListaDados?>
